[build]
dist = "target/site/pkg"    # This sets the output folder for the build
public_url = "/"            # The base URL where your site will be hosted

[scss]
source = "style/main.scss"
output = "style/main.css"

[watch]
# Optional: Specify directories or files to watch during development
paths = ["src", "assets"]