# .github/workflows/deploy.yml
name: Build and Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Rust
        run: |
          curl https://sh.rustup.rs -sSf | sh -s -- -y
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - name: Cache Rust Toolchain and Dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo
            ~/.rustup
          key: rust-${{ runner.os }}-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            rust-${{ runner.os }}-

      - name: Install wasm32 Target
        run: rustup target add wasm32-unknown-unknown

      - name: Cache Cargo Registry and Git Index
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
          key: cargo-registry-${{ runner.os }}-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            cargo-registry-${{ runner.os }}-

      - name: Cache Leptos CLI
        uses: actions/cache@v4
        with:
          path: ~/.cargo/bin/cargo-leptos
          key: leptos-cli-${{ runner.os }}-latest
          restore-keys: |
            leptos-cli-${{ runner.os }}-

      - name: Install Leptos CLI if not cached
        if: steps.leptos-cache.outputs.cache-hit != 'true'
        run: cargo install cargo-leptos

      - name: Cache Trunk
        uses: actions/cache@v4
        with:
          path: ~/.cargo/bin/trunk
          key: trunk-cli-${{ runner.os }}-latest
          restore-keys: |
            trunk-cli-${{ runner.os }}-

      - name: Install Trunk if not cached
        if: steps.trunk-cache.outputs.cache-hit != 'true'
        run: cargo install trunk

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Sass
        run: npm install -g sass

      - name: Compile SCSS to CSS
        run: sass style/main.scss style/main.css

      - name: Lint Rust Codebase
        run: cargo fmt -- --check

      - name: Run Rust Tests
        run: cargo test --release

      - name: Ensure target/site Directory Exists
        run: mkdir -p target/site

      - name: Build Leptos Site with Trunk
        run: trunk build --release

      - name: Move Compiled CSS to Deployment Directory
        run: |
          mkdir -p target/site/pkg/style
          cp style/main.css target/site/pkg/style/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./target/site