name: Build and Deploy to Cloudflare Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Rust toolchain
        run: |
          rustup toolchain install stable
          rustup default stable
          rustup target add wasm32-unknown-unknown

      - name: Install Leptos CLI
        run: cargo install --locked cargo-leptos

      - name: Build Leptos site
        run: cargo leptos build --release

      - name: Move build output to root
        run: mv target/site/pkg/* target/site/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./target/site