# .github/workflows/deploy.yml
name: Build and Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Rust Toolchain and Components if Necessary
        run: |
          # Install Rust if not already installed
          if ! command -v rustc &> /dev/null; then
            curl https://sh.rustup.rs -sSf | sh -s -- -y
            echo "$HOME/.cargo/bin" >> $GITHUB_PATH
          else
            echo "Rust is already installed."
          fi

          # Update Rust to the latest stable version
          echo "Updating Rust to the latest stable version..."
          rustup update

          # Install required components if missing
          for component in rustfmt rust-analyzer; do
            if ! rustup component list --installed | grep -q "^${component} "; then
              echo "Installing ${component}."
              rustup component add $component
            else
              echo "${component} is already installed."
            fi
          done

      - name: Cache Rust Toolchain and Dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo
            ~/.rustup
          key: rust-${{ runner.os }}-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            rust-${{ runner.os }}-

      - name: Install wasm32 Target
        run: rustup target add wasm32-unknown-unknown

      - name: Cache Cargo Registry and Git Index
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
          key: cargo-registry-${{ runner.os }}-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            cargo-registry-${{ runner.os }}-

      - name: Check and Install Leptos CLI
        run: |
          latest_version=$(cargo search cargo-leptos | grep -oP '(?<=^cargo-leptos = ")[^"]*')
          installed_version=$(cargo-leptos --version 2>/dev/null | awk '{print $2}' || echo "none")
          echo "Latest cargo-leptos version: $latest_version"
          echo "Installed cargo-leptos version: $installed_version"
          if [ "$installed_version" != "$latest_version" ]; then
            echo "Installing/updating cargo-leptos to version $latest_version"
            cargo install cargo-leptos --force --locked
          else
            echo "cargo-leptos is up-to-date"
          fi

      - name: Cache Trunk
        uses: actions/cache@v4
        with:
          path: ~/.cargo/bin/trunk
          key: trunk-cli-${{ runner.os }}-latest
          restore-keys: |
            trunk-cli-${{ runner.os }}-

      - name: Check and Install Trunk
        run: |
          latest_version=$(cargo search trunk | grep -oP '(?<=^trunk = ")[^"]*')
          installed_version=$(trunk --version 2>/dev/null | awk '{print $2}' || echo "none")
          echo "Latest trunk version: $latest_version"
          echo "Installed trunk version: $installed_version"
          if [ "$installed_version" != "$latest_version" ]; then
            echo "Installing/updating trunk to version $latest_version"
            cargo install trunk --force
          else
            echo "Trunk is up-to-date"
          fi

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      
      - name: Cache npm Global Packages
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: npm-global-sass-${{ runner.os }}-latest
          restore-keys: |
            npm-global-sass-${{ runner.os }}-

      - name: Check and Install Sass
        run: |
          latest_version=$(npm view sass version)
          installed_version=$(sass --version 2>/dev/null | awk '{print $2}' || echo "none")
          echo "Latest Sass version: $latest_version"
          echo "Installed Sass version: $installed_version"
          if [ "$installed_version" != "$latest_version" ]; then
            echo "Installing/updating Sass to version $latest_version"
            npm install -g sass
          else
            echo "Sass is up-to-date"
          fi

      - name: Lint Rust Codebase
        run: cargo fmt -- --check

      - name: Run Rust Tests
        run: cargo test --release
      
      - name: Compile SCSS to CSS
        run: sass style/main.scss style/main.css
      
      - name: Ensure target/site Directory Exists
        run: mkdir -p target/site

      - name: Move Compiled CSS to Deployment Directory
        run: |
          mkdir -p target/site/style
          cp style/main.css target/site/style/

      - name: Build Leptos Site with Trunk
        run: trunk build --release

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./target/site