name: Build and Deploy to Cloudflare Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Check out the latest code from the 'main' branch.
      #    Ensures the workflow operates on the latest code changes.
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Cache the Rust toolchain to speed up builds.
      #    Reuse the toolchain if 'Cargo.lock' hasn't changed.
      #    This reduces toolchain installation time.
      - name: Cache Rust toolchain
        id: rust-cache
        uses: actions/cache@v4
        with:
          path: ~/.cargo
          key: rust-toolchain-${{ runner.os }}-${{ hashFiles('Cargo.lock') }}
          restore-keys: |
            rust-toolchain-${{ runner.os }}-

      # 3. Install Rust and the WebAssembly target.
      #    Ensures all required components are available for building.
      - name: Install Rust toolchain and wasm32 target
        run: |
          rustup toolchain install stable
          rustup default stable
          rustup target add wasm32-unknown-unknown

      # 4. Cache the Cargo registry and index to minimize network usage.
      #    Helps avoid downloading dependencies repeatedly.
      - name: Cache Cargo registry and index
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
          key: cargo-${{ runner.os }}-${{ hashFiles('Cargo.lock') }}
          restore-keys: |
            cargo-${{ runner.os }}-

      # 5. Cache Leptos CLI to avoid reinstalling on every run.
      #    Uses version-specific cache to ensure compatibility.
      - name: Cache Leptos CLI
        id: leptos-cache
        uses: actions/cache@v4
        with:
          path: ~/.cargo/bin/cargo-leptos
          key: leptos-cli-${{ runner.os }}-v0.6.15
          restore-keys: |
            leptos-cli-${{ runner.os }}-

      # 6. Install Leptos CLI if it's not in the cache.
      #    Guarantees the CLI is available for the build process.
      - name: Install Leptos CLI
        if: steps.leptos-cache.outputs.cache-hit != 'true'
        run: cargo install --locked cargo-leptos

      # 7. Cache Trunk to avoid unnecessary reinstalls.
      #    Improves efficiency by storing the compiled Trunk binary.
      - name: Cache Trunk
        id: trunk-cache
        uses: actions/cache@v4
        with:
          path: ~/.cargo/bin/trunk
          key: trunk-cli-${{ runner.os }}-v0.20.3
          restore-keys: |
            trunk-cli-${{ runner.os }}-

      # 8. Install Trunk if it's not cached.
      #    Required for building the static site assets.
      - name: Install Trunk for static assets
        if: steps.trunk-cache.outputs.cache-hit != 'true'
        run: cargo install trunk

      # 9. Create the 'target/site' directory if it doesn't exist.
      #    Prepares the directory structure for the build output.
      - name: Ensure target/site directory exists
        run: mkdir -p target/site

      # 10. Build the Leptos site using Trunk in release mode.
      #     Produces optimized assets for deployment.
      - name: Build Leptos site for CSR with Trunk
        run: trunk build --release

      # 11. Deploy the built site to the 'gh-pages' branch.
      #     Publishes the contents of 'target/site/pkg' to GitHub Pages.
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./target/site/pkg